[2025-04-16T00:29:09.274+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-16T00:28:48.778631+00:00 [queued]>
[2025-04-16T00:29:09.278+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-16T00:28:48.778631+00:00 [queued]>
[2025-04-16T00:29:09.278+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-16T00:29:09.288+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): populate_enriched_table> on 2025-04-16 00:28:48.778631+00:00
[2025-04-16T00:29:09.298+0000] {standard_task_runner.py:60} INFO - Started process 26941 to run task
[2025-04-16T00:29:09.303+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'populate_sampled_songs_enriched', 'populate_enriched_table', 'manual__2025-04-16T00:28:48.778631+00:00', '--job-id', '262', '--raw', '--subdir', 'DAGS_FOLDER/populate_enriched_table_dag.py', '--cfg-path', '/tmp/tmp9wmm1gpo']
[2025-04-16T00:29:09.306+0000] {standard_task_runner.py:88} INFO - Job 262: Subtask populate_enriched_table
[2025-04-16T00:29:09.343+0000] {task_command.py:423} INFO - Running <TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-16T00:28:48.778631+00:00 [running]> on host d8146153ddc3
[2025-04-16T00:29:09.399+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='populate_sampled_songs_enriched' AIRFLOW_CTX_TASK_ID='populate_enriched_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-16T00:28:48.778631+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-16T00:28:48.778631+00:00'
[2025-04-16T00:29:09.400+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.34
[2025-04-16T00:29:09.401+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-16T00:29:09.660+0000] {cursor.py:1028} INFO - query: [CREATE TABLE IF NOT EXISTS SAMPLED_SONGS_ENRICHED ( title STRING, youtube_url ST...]
[2025-04-16T00:29:09.726+0000] {cursor.py:1041} INFO - query execution done
[2025-04-16T00:29:09.727+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-04-16T00:29:09.727+0000] {cursor.py:1028} INFO - query: [MERGE INTO SAMPLED_SONGS_ENRICHED AS target USING ( SELECT title, youtube_url, s...]
[2025-04-16T00:29:09.818+0000] {cursor.py:1041} INFO - query execution done
[2025-04-16T00:29:09.824+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/backend/rag_pipeline/populate_enriched_table.py", line 48, in populate_enriched_table
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1132, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 000904 (42000): 01bbb75d-020d-0c64-000d-5acb000fb25e: SQL compilation error: error line 18 at position 12
invalid identifier 'VIDEO_DURATION'
[2025-04-16T00:29:09.831+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=populate_sampled_songs_enriched, task_id=populate_enriched_table, execution_date=20250416T002848, start_date=20250416T002909, end_date=20250416T002909
[2025-04-16T00:29:09.842+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 262 for task populate_enriched_table (000904 (42000): 01bbb75d-020d-0c64-000d-5acb000fb25e: SQL compilation error: error line 18 at position 12
invalid identifier 'VIDEO_DURATION'; 26941)
[2025-04-16T00:29:09.860+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-16T00:29:09.874+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
