[2025-04-12T16:57:26.903+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-12T16:57:25.341701+00:00 [queued]>
[2025-04-12T16:57:26.906+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-12T16:57:25.341701+00:00 [queued]>
[2025-04-12T16:57:26.906+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-12T16:57:26.912+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): populate_enriched_table> on 2025-04-12 16:57:25.341701+00:00
[2025-04-12T16:57:26.915+0000] {standard_task_runner.py:60} INFO - Started process 278 to run task
[2025-04-12T16:57:26.917+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'populate_sampled_songs_enriched', 'populate_enriched_table', 'manual__2025-04-12T16:57:25.341701+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/populate_enriched_table_dag.py', '--cfg-path', '/tmp/tmpqqwujg2w']
[2025-04-12T16:57:26.918+0000] {standard_task_runner.py:88} INFO - Job 190: Subtask populate_enriched_table
[2025-04-12T16:57:26.942+0000] {task_command.py:423} INFO - Running <TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-12T16:57:25.341701+00:00 [running]> on host cea305b355c8
[2025-04-12T16:57:26.970+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='populate_sampled_songs_enriched' AIRFLOW_CTX_TASK_ID='populate_enriched_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T16:57:25.341701+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T16:57:25.341701+00:00'
[2025-04-12T16:57:26.971+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.34
[2025-04-12T16:57:26.972+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-12T16:57:27.330+0000] {cursor.py:1028} INFO - query: [CREATE TABLE IF NOT EXISTS SAMPLED_SONGS_ENRICHED ( title STRING, youtube_url ST...]
[2025-04-12T16:57:27.395+0000] {cursor.py:1041} INFO - query execution done
[2025-04-12T16:57:27.395+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-04-12T16:57:27.395+0000] {cursor.py:1028} INFO - query: [SELECT * FROM SAMPLED_SONGS_STAGING]
[2025-04-12T16:57:27.478+0000] {cursor.py:1041} INFO - query execution done
[2025-04-12T16:57:27.478+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-04-12T16:57:27.510+0000] {cursor.py:1028} INFO - query: [MERGE INTO SAMPLED_SONGS_ENRICHED AS target USING (SELECT 'https://www.youtube.c...]
[2025-04-12T16:57:27.597+0000] {cursor.py:1041} INFO - query execution done
[2025-04-12T16:57:27.610+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/backend/rag_pipeline/populate_enriched_table.py", line 88, in populate_enriched_table
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 1132, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 002020 (21S01): 01bba4b9-020d-00ac-000d-5acb00066cf2: SQL compilation error:
Insert value list does not match column list expecting 19 but got 20
[2025-04-12T16:57:27.617+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=populate_sampled_songs_enriched, task_id=populate_enriched_table, execution_date=20250412T165725, start_date=20250412T165726, end_date=20250412T165727
[2025-04-12T16:57:27.626+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 190 for task populate_enriched_table (002020 (21S01): 01bba4b9-020d-00ac-000d-5acb00066cf2: SQL compilation error:
Insert value list does not match column list expecting 19 but got 20; 278)
[2025-04-12T16:57:27.643+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-12T16:57:27.669+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
