[2025-04-12T16:54:18.807+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-12T16:54:16.351024+00:00 [queued]>
[2025-04-12T16:54:18.812+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-12T16:54:16.351024+00:00 [queued]>
[2025-04-12T16:54:18.812+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-12T16:54:18.818+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): populate_enriched_table> on 2025-04-12 16:54:16.351024+00:00
[2025-04-12T16:54:18.823+0000] {standard_task_runner.py:60} INFO - Started process 224 to run task
[2025-04-12T16:54:18.825+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'populate_sampled_songs_enriched', 'populate_enriched_table', 'manual__2025-04-12T16:54:16.351024+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/populate_enriched_table_dag.py', '--cfg-path', '/tmp/tmpb_9yu61w']
[2025-04-12T16:54:18.826+0000] {standard_task_runner.py:88} INFO - Job 188: Subtask populate_enriched_table
[2025-04-12T16:54:18.862+0000] {task_command.py:423} INFO - Running <TaskInstance: populate_sampled_songs_enriched.populate_enriched_table manual__2025-04-12T16:54:16.351024+00:00 [running]> on host cea305b355c8
[2025-04-12T16:54:18.891+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='populate_sampled_songs_enriched' AIRFLOW_CTX_TASK_ID='populate_enriched_table' AIRFLOW_CTX_EXECUTION_DATE='2025-04-12T16:54:16.351024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-12T16:54:16.351024+00:00'
[2025-04-12T16:54:18.892+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.8.18, Platform: Linux-6.12.5-linuxkit-aarch64-with-glibc2.34
[2025-04-12T16:54:18.893+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-12T16:54:19.644+0000] {cursor.py:1028} INFO - query: [CREATE TABLE IF NOT EXISTS SAMPLED_SONGS_ENRICHED ( title STRING, youtube_url ST...]
[2025-04-12T16:54:19.753+0000] {cursor.py:1041} INFO - query execution done
[2025-04-12T16:54:19.754+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-04-12T16:54:19.754+0000] {cursor.py:1028} INFO - query: [SELECT * FROM SAMPLED_SONGS_STAGING]
[2025-04-12T16:54:20.008+0000] {cursor.py:1041} INFO - query execution done
[2025-04-12T16:54:20.009+0000] {cursor.py:1205} INFO - Number of results in first chunk: 1
[2025-04-12T16:54:20.025+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1477, in _process_params_pyformat
    ret = tuple(res)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1523, in _process_single_param
    return _quote(escape(to_snowflake(param)))
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/converter.py", line 469, in to_snowflake
    return getattr(self, f"_{type_name}_to_snowflake")(value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/converter.py", line 641, in __getattr__
    raise ProgrammingError(
snowflake.connector.errors.ProgrammingError: 255001: 255001: Binding data in type (timestamp) is not supported.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/backend/rag_pipeline/populate_enriched_table.py", line 64, in populate_enriched_table
    cursor.execute("""
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 996, in execute
    query = self._preprocess_pyformat_query(command, params)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 806, in _preprocess_pyformat_query
    processed_params = self._connection._process_params_pyformat(params, self)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/connection.py", line 1481, in _process_params_pyformat
    Error.errorhandler_wrapper(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 252004: 252004: Failed processing pyformat-parameters; 255001: 255001: Binding data in type (timestamp) is not supported.
[2025-04-12T16:54:20.034+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=populate_sampled_songs_enriched, task_id=populate_enriched_table, execution_date=20250412T165416, start_date=20250412T165418, end_date=20250412T165420
[2025-04-12T16:54:20.047+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 188 for task populate_enriched_table (252004: 252004: Failed processing pyformat-parameters; 255001: 255001: Binding data in type (timestamp) is not supported.; 224)
[2025-04-12T16:54:20.086+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-12T16:54:20.110+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
